[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # Disable secrets scanning for build output
  SECRETS_SCAN_OMIT_PATHS = ".next/**,_next/**,.netlify/**"

# Essential: Enable Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Fix static asset serving - critical for _next/static files
[[redirects]]
  from = "/_next/static/*"
  to = "/.next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200

# Handle Next.js rewrites and dynamic routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200

# Static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables required for deployment
# Set these in Netlify UI:
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY  
# SUPABASE_SERVICE_ROLE_KEY