[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # Disable secrets scanning for build output
  SECRETS_SCAN_OMIT_PATHS = ".next/**,_next/**,.netlify/**"

# Essential: Enable Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables required for deployment
# Set these in Netlify UI:
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY  
# SUPABASE_SERVICE_ROLE_KEY